# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "783817f658a30aac587e9d02442aa686"
name = "whishlist"
handle = "whishlist-25"
application_url = "https://hughes-history-ag-leaf.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://hughes-history-ag-leaf.trycloudflare.com/auth/callback", "https://hughes-history-ag-leaf.trycloudflare.com/auth/shopify/callback", "https://hughes-history-ag-leaf.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
